spring:
  application:
    name: notification-server

  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: directory.update

server:
  port: 5004
